<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="35305" started-at="2019-01-19T06:02:52Z" finished-at="2019-01-19T06:03:27Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="35305" started-at="2019-01-19T06:02:52Z" finished-at="2019-01-19T06:03:27Z">
      <class name="com.selenium.WebdriverProj.WebDriverwithTestng.MercuryHomePageTitle">
        <test-method status="PASS" signature="testsetup()[pri:0, instance:com.selenium.WebdriverProj.WebDriverwithTestng.MercuryHomePageTitle@9629756]" name="testsetup" is-config="true" duration-ms="17106" started-at="2019-01-19T11:32:52Z" finished-at="2019-01-19T11:33:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testsetup -->
        <test-method status="FAIL" signature="verifytitle()[pri:0, instance:com.selenium.WebdriverProj.WebDriverwithTestng.MercuryHomePageTitle@9629756]" name="verifytitle" duration-ms="17449" started-at="2019-01-19T11:33:09Z" finished-at="2019-01-19T11:33:27Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Mercury] but found [Find a Flight: Mercury Tours:]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Mercury] but found [Find a Flight: Mercury Tours:]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.selenium.WebdriverProj.WebDriverwithTestng.MercuryHomePageTitle.verifytitle(MercuryHomePageTitle.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifytitle -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.selenium.WebdriverProj.WebDriverwithTestng.MercuryHomePageTitle@9629756]" name="tearDown" is-config="true" duration-ms="726" started-at="2019-01-19T11:33:27Z" finished-at="2019-01-19T11:33:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.selenium.WebdriverProj.WebDriverwithTestng.MercuryHomePageTitle -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
